#!/usr/bin/env bash
# mTLS usage examples with curl
# Replace the paths with the files generated by issue-cert.sh

GATEWAY="https://api.zuplo.baas.io"
CERT_SERVICE="https://certs.baas.io"
CERT="./certs-output/MY_CERT_ID.crt"
KEY="./certs-output/MY_CERT_ID.key"
TENANT_ID="my-tenant-uuid"

echo "=== Issue a certificate ==="
curl -X POST "$CERT_SERVICE/v1/certificates" \
  -H "Content-Type: application/json" \
  -H "X-Tenant-Id: $TENANT_ID" \
  -d '{
    "commonName": "partner-a.api.baas.io",
    "organization": "Financial Partner A Inc",
    "country": "US",
    "ttl": "2160h"
  }' | jq .

echo ""
echo "=== List tenant certificates ==="
curl "$CERT_SERVICE/v1/certificates" \
  -H "X-Tenant-Id: $TENANT_ID" | jq .

echo ""
echo "=== Call protected API via mTLS ==="
curl --cert "$CERT" \
     --key  "$KEY" \
     -H "Content-Type: application/json" \
     "$GATEWAY/v1/certificates" | jq .

echo ""
echo "=== Revoke a certificate ==="
curl -X DELETE "$CERT_SERVICE/v1/certificates/MY_CERT_ID" \
  -H "Content-Type: application/json" \
  -H "X-Tenant-Id: $TENANT_ID" \
  -d '{"reason": "keyCompromise"}'
